name: Sync NPM Token from Repository Secrets

on:
  workflow_dispatch:

jobs:
  write-npmrc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create .npmrc from secret
        run: |
          if [[ -z "${{ secrets.NPM_TOKEN }}" ]]; then
            echo "NPM_TOKEN secret missing" >&2; exit 1
          fi
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
      - name: Save .npmrc as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: npmrc
          path: .npmrc
      - name: Mask token in logs
        run: echo "token set"